export const VOICE_LINES = [
  "One day maybe you, maybe me, but today is not that day, my friend.",
  "Easy peasy lemon squeezy.",
  "I'm the young sniper from Poland!",
  "My friend, don't worry, this is Pasha power.",
  "No ace, no win. Simple.",
  "You play like my little brother... and my brother is in kindergarten.",
  "Don't cry, don't be baby.",
  "If you give me AWP, I give you win!",
  "Too easy for Pasha London School!",
  "Why you bully me, my friend?",
  "For my family, I fight every day.",
  "The real man is not afraid to cry.",
  "You must believe in yourself. Never give up, my friend.",
  "Sometimes you win, sometimes you lose, but never stop fighting.",
  "Life is not only CS:GO. Family is the most important thing.",
  "When you lose, you learn more than when you win.",
  "Be a good man, not only a good player.",
  "With great power comes great responsibility.",
  "My friend, I'm too strong. I eat gym and go to kebab.",
  "Kebabs and headshots—Pasha style.",
  "You see this muscle, my friend? It’s not only for gym, it’s for headshots.",
  "Big biceps, big heart, my friend.",
  "I buy Deagle. If I don’t kill, it’s because the game is broken.",
  "I save money like Polish economy.",
  "PashaBiceps never save... except for family.",
  "You rush B? I rush gym!",
  "Pasha no camper, Pasha hunter!",
  "This is not mistake; this is strategy.",
  "I’m like ninja, but with biceps.",
  "Give me AK, and I give them pain.",
  "Don’t trust the no-scope. Always trust the biceps.",
  "If you camp, you are not true player.",
  "The AWP is like my second wife—beautiful and deadly.",
  "If you play with heart, you can win anything, my friend.",
  "Counter-Strike is life, but don’t forget your real life.",
  "I don’t tilt, my friend. I just adapt.",
  "My flashbang is like Polish sausage—everybody loves it.",
  "I have two kids, my friend. And I treat my AK like the third one.",
  "Headshots come easy when you train like me!",
  "My friend, if you are scared, go play Minecraft.",
  "You can’t fake my biceps, just like you can’t fake my skills.",
  "It’s not luck; it’s Pasha style!",
  "This is not game over; this is just the beginning.",
  "Teamwork makes the dream work, my friend.",
  "You shoot me, but I shoot better.",
  "My biceps so big, my T-shirt scared.",
  "I don’t need radar, my friend. I feel the game in my blood.",
  "When I hold AWP, enemies uninstall the game.",
  "You cannot stop Pasha. You can only delay him.",
  "Who needs tactics when you have muscle memory?",
  "My crosshair is like GPS: always on target.",
  "Polish power never goes eco!",
  "Rush B? No, my friend. We rush victory.",
  "No fear, no tilt, only headshots.",
  "If you lose, it’s your fault. If I lose, it’s the game’s fault.",
  "I play smart, not hard... but also hard, my friend.",
  "When I die, it’s part of the plan.",
  "PashaBiceps doesn’t fake. I plant or I kill.",
  "Kebab > tactical timeout.",
  "When I clutch, my wife claps.",
  "You call it luck, I call it skill.",
  "I don’t need smokes; I need headshots.",
  "When Pasha enters the server, the server flexes.",
  "I don’t need to check corners. Corners are scared of me.",
  "If Pasha loses, it’s because he wanted you to feel happy.",
  "You cannot tilt a mountain, my friend, and I am the mountain.",
  "If we lose, we train harder. If we win, we train hardest.",
  "Fail once, win twice.",
  "In Counter-Strike and life, always push forward.",
  "You think you have me? My comeback is stronger than your best shot.",
  "Pasha does not camp; Pasha conquers.",
  "Headshot is not luck; it’s lifestyle.",
  "When I shoot, I shoot with purpose.",
  "Never stop moving, never stop improving.",
  "You can kill Pasha, but you can’t kill his legacy.",
  "With big biceps comes big responsibility.",
  "My friend, every game I play is like a gym session for my brain.",
  "Why play for kills when you can play for glory?",
  "AWP in my hand, the game in my control.",
  "If my shot doesn’t kill, it’s because I let you live.",
];
